In [1]:
import pandas as pd

In [2]:
import requests 

docs_url = 'https://github.com/alexeygrigorev/llm-rag-workshop/raw/main/notebooks/documents.json'
docs_response = requests.get(docs_url)
documents_raw = docs_response.json()

documents = []

for course in documents_raw:
    course_name = course['course']

    for doc in course['documents']:
        doc['course'] = course_name
        documents.append(doc)

In [3]:
documents[0:2]

[{'text': "The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first  “Office Hours'' live.1\nSubscribe to course public Google Calendar (it works from Desktop only).\nRegister before the course starts using this link.\nJoin the course Telegram channel with announcements.\nDon’t forget to register in DataTalks.Club's Slack and join the channel.",
  'section': 'General course-related questions',
  'question': 'Course - When will the course start?',
  'course': 'data-engineering-zoomcamp'},
 {'text': 'GitHub - DataTalksClub data-engineering-zoomcamp#prerequisites',
  'section': 'General course-related questions',
  'question': 'Course - What are the prerequisites for this course?',
  'course': 'data-engineering-zoomcamp'}]

In [4]:
documents_raw[0]['course']

'data-engineering-zoomcamp'

In [5]:
#documents_raw[0]

In [6]:
documents[0]

{'text': "The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first  “Office Hours'' live.1\nSubscribe to course public Google Calendar (it works from Desktop only).\nRegister before the course starts using this link.\nJoin the course Telegram channel with announcements.\nDon’t forget to register in DataTalks.Club's Slack and join the channel.",
 'section': 'General course-related questions',
 'question': 'Course - When will the course start?',
 'course': 'data-engineering-zoomcamp'}

In [7]:
import pandas as pd

df = pd.DataFrame(documents, columns=['course', 'section', 'question', 'text'])
df.head()

course                           section  \
0  data-engineering-zoomcamp  General course-related questions   
1  data-engineering-zoomcamp  General course-related questions   
2  data-engineering-zoomcamp  General course-related questions   
3  data-engineering-zoomcamp  General course-related questions   
4  data-engineering-zoomcamp  General course-related questions   

                                            question  \
0               Course - When will the course start?   
1  Course - What are the prerequisites for this c...   
2  Course - Can I still join the course after the...   
3  Course - I have registered for the Data Engine...   
4   Course - What can I do before the course starts?   

                                                text  
0  The purpose of this document is to capture fre...  
1  GitHub - DataTalksClub data-engineering-zoomca...  
2  Yes, even if you don't register, you're still ...  
3  You don't need it. You're accepted. You can al...  
4  You can start by installing and setting up all...

In [8]:
df['course'].value_counts()

course
data-engineering-zoomcamp    435
machine-learning-zoomcamp    375
mlops-zoomcamp               138
Name: count, dtype: int64

In [9]:
df[df['course'] == 'data-engineering-zoomcamp']

course                           section  \
0    data-engineering-zoomcamp  General course-related questions   
1    data-engineering-zoomcamp  General course-related questions   
2    data-engineering-zoomcamp  General course-related questions   
3    data-engineering-zoomcamp  General course-related questions   
4    data-engineering-zoomcamp  General course-related questions   
..                         ...                               ...   
430  data-engineering-zoomcamp           Workshop 2 - RisingWave   
431  data-engineering-zoomcamp           Workshop 2 - RisingWave   
432  data-engineering-zoomcamp           Workshop 2 - RisingWave   
433  data-engineering-zoomcamp          Triggers in Mage via CLI   
434  data-engineering-zoomcamp          Triggers in Mage via CLI   

                                              question  \
0                 Course - When will the course start?   
1    Course - What are the prerequisites for this c...   
2    Course - Can I still join the course after the...   
3    Course - I have registered for the Data Engine...   
4     Course - What can I do before the course starts?   
..                                                 ...   
430  Unable to Open Dashboard as xdg-open doesn’t o...   
431  Resolving Python Interpreter Path Inconsistenc...   
432                    How does windowing work in Sql?   
433  Encountering the error "ModuleNotFoundError: N...   
434                                     Basic Commands   

                                                  text  
0    The purpose of this document is to capture fre...  
1    GitHub - DataTalksClub data-engineering-zoomca...  
2    Yes, even if you don't register, you're still ...  
3    You don't need it. You're accepted. You can al...  
4    You can start by installing and setting up all...  
..                                                 ...  
430  Refer to the solution given in the first solut...  
431  Example Error:\nWhen attempting to execute a P...  
432  Ans : Windowing in streaming SQL involves defi...  
433  Python 3.12.1, is not compatible with kafka-py...  
434  Docker Commands\n# Create a Docker Image from ...  

[435 rows x 4 columns]

## Vectorization ## 

# bag of words

In [10]:
docs_example = [
    "Course starts on 15th Jan 2024",
    "Prerequisites listed on GitHub",
    "Submit homeworks after start date",
    "Registration not required for participation",
    "Setup Google Cloud and Python before course"
]

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(stop_words='english')
X = cv.fit_transform(docs_example)

names = cv.get_feature_names_out()

In [12]:
X = cv.transform(docs_example)

In [13]:
names

array(['15th', '2024', 'cloud', 'course', 'date', 'github', 'google',
       'homeworks', 'jan', 'listed', 'participation', 'prerequisites',
       'python', 'registration', 'required', 'setup', 'start', 'starts',
       'submit'], dtype=object)

In [14]:
X.shape

(5, 19)

In [25]:
X

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 20 stored elements and shape (5, 19)>

In [15]:
X.toarray()

array([[1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0]])

In [16]:
len(names)

19

In [17]:
X.todense()

matrix([[1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0],
        [0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0]])

In [18]:
pd.DataFrame(X.todense(), columns= cv.get_feature_names_out())

15th  2024  cloud  course  date  github  google  homeworks  jan  listed  \
0     1     1      0       1     0       0       0          0    1       0   
1     0     0      0       0     0       1       0          0    0       1   
2     0     0      0       0     1       0       0          1    0       0   
3     0     0      0       0     0       0       0          0    0       0   
4     0     0      1       1     0       0       1          0    0       0   

   participation  prerequisites  python  registration  required  setup  start  \
0              0              0       0             0         0      0      0   
1              0              1       0             0         0      0      0   
2              0              0       0             0         0      0      1   
3              1              0       0             1         1      0      0   
4              0              0       1             0         0      1      0   

   starts  submit  
0       1       0  
1       0       0  
2       0       1  
3       0       0  
4       0       0

In [19]:
pd.DataFrame(X.todense(), columns= cv.get_feature_names_out()).T

0  1  2  3  4
15th           1  0  0  0  0
2024           1  0  0  0  0
cloud          0  0  0  0  1
course         1  0  0  0  1
date           0  0  1  0  0
github         0  1  0  0  0
google         0  0  0  0  1
homeworks      0  0  1  0  0
jan            1  0  0  0  0
listed         0  1  0  0  0
participation  0  0  0  1  0
prerequisites  0  1  0  0  0
python         0  0  0  0  1
registration   0  0  0  1  0
required       0  0  0  1  0
setup          0  0  0  0  1
start          0  0  1  0  0
starts         1  0  0  0  0
submit         0  0  1  0  0

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

cv = TfidfVectorizer(stop_words='english', min_df = 5)
X = cv.fit_transform(df.text)

names = cv.get_feature_names_out()

df_docs = pd.DataFrame(X.toarray(), columns=names)
df_docs.round(2)

01   02   03   04   05   06   09   10  100   11  ...  y_val  yaml  year  \
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.00   0.0   
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.00   0.0   
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.00   0.0   
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.00   0.0   
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.00   0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...   ...   ...   
943  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.00   0.0   
944  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.00   0.0   
945  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.17   0.0   
946  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.00   0.0   
947  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.00   0.0   

     yellow  yellow_tripdata_2021   yes   yml  youtube  zip  zoomcamp  
0       0.0                   0.0  0.00  0.00      0.0  0.0      0.00  
1       0.0                   0.0  0.00  0.00      0.0  0.0      0.43  
2       0.0                   0.0  0.28  0.00      0.0  0.0      0.00  
3       0.0                   0.0  0.00  0.00      0.0  0.0      0.00  
4       0.0                   0.0  0.00  0.00      0.0  0.0      0.00  
..      ...                   ...   ...   ...      ...  ...       ...  
943     0.0                   0.0  0.00  0.11      0.0  0.0      0.00  
944     0.0                   0.0  0.00  0.00      0.0  0.0      0.00  
945     0.0                   0.0  0.00  0.00      0.0  0.0      0.00  
946     0.0                   0.0  0.00  0.00      0.0  0.0      0.00  
947     0.0                   0.0  0.00  0.00      0.0  0.0      0.15  

[948 rows x 1333 columns]

# Query- DoC Similarity

In [21]:
query = "Do I need to know python to sign up for the January course?"

q = cv.transform([query])
q.toarray()

array([[0., 0., 0., ..., 0., 0., 0.]], shape=(1, 1333))

In [22]:
query_dict = dict(zip(names, q.toarray()[0]))
#query_dict

In [23]:
a = [k for k, v in query_dict.items() if v >0]

In [24]:
a

['course', 'know', 'need', 'python', 'sign']

In [25]:
query_dict['know']

np.float64(0.5608269127690405)

In [26]:
X.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.42896052],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.14842753]], shape=(948, 1333))

In [27]:
doc_dict = dict(zip(names, X.toarray()[2]))
#doc_dict

In [28]:
a = [k for k, v in doc_dict.items() if v >0]

In [29]:
a

['don', 'final', 'homeworks', 'projects', 'register', 'submit', 'yes']

In [43]:
#X.dot(q.T).toarray()

In [31]:
from sklearn.metrics.pairwise import cosine_similarity

In [32]:
score = cosine_similarity(X, q).flatten()

In [33]:
import numpy as np

In [34]:
np.argsort(score)[-5:]

array([764,  27, 806, 577, 445])

In [35]:
df.iloc[764].text

'If you have submitted two projects (and peer-reviewed at least 3 course-mates’ projects for each submission), you will get the certificate for the course. According to the course coordinator, Alexey Grigorev, only two projects are needed to get the course certificate.\n(optional) David Odimegwu'

In [36]:
df.head()

course                           section  \
0  data-engineering-zoomcamp  General course-related questions   
1  data-engineering-zoomcamp  General course-related questions   
2  data-engineering-zoomcamp  General course-related questions   
3  data-engineering-zoomcamp  General course-related questions   
4  data-engineering-zoomcamp  General course-related questions   

                                            question  \
0               Course - When will the course start?   
1  Course - What are the prerequisites for this c...   
2  Course - Can I still join the course after the...   
3  Course - I have registered for the Data Engine...   
4   Course - What can I do before the course starts?   

                                                text  
0  The purpose of this document is to capture fre...  
1  GitHub - DataTalksClub data-engineering-zoomca...  
2  Yes, even if you don't register, you're still ...  
3  You don't need it. You're accepted. You can al...  
4  You can start by installing and setting up all...

In [37]:
df.columns

Index(['course', 'section', 'question', 'text'], dtype='object')

In [40]:
fields = ['course', 'section', 'question', 'text']

In [57]:
matrices = {}
vectorizers = {}
for f in fields:
    cv = TfidfVectorizer(stop_words='english', min_df = 5)
    X = cv.fit_transform(df[f])
    matrices[f] = X
    vectorizers[f] = cv

In [42]:
matrices

{'course': <Compressed Sparse Row sparse matrix of dtype 'float64'
 	with 2706 stored elements and shape (948, 6)>,
 'section': <Compressed Sparse Row sparse matrix of dtype 'float64'
 	with 3090 stored elements and shape (948, 66)>,
 'question': <Compressed Sparse Row sparse matrix of dtype 'float64'
 	with 3431 stored elements and shape (948, 291)>,
 'text': <Compressed Sparse Row sparse matrix of dtype 'float64'
 	with 23808 stored elements and shape (948, 1333)>}

In [44]:
n= len(df)

In [58]:
vectorizers

{'course': TfidfVectorizer(min_df=5, stop_words='english'),
 'section': TfidfVectorizer(min_df=5, stop_words='english'),
 'question': TfidfVectorizer(min_df=5, stop_words='english'),
 'text': TfidfVectorizer(min_df=5, stop_words='english')}

In [79]:
score = np.zeros(n)
query = "I just discovered the course, is it too late to join?"
boosts = {
    'question' : 3
}
for f in fields:
    q = vectorizers[f].transform([query])
    x = matrices[f]
    f_score = cosine_similarity(x, q).flatten()
    boost = boosts.get(f,1)
    score = score + boost*f_score
    

In [80]:
#score

In [81]:
filters = {
    'course':'data-engineering-zoomcamp'
}

In [82]:
for field, value in filters.items():
    mask = (df[field] == value).astype(int).values
    score = score * mask

In [83]:
score

array([3.52985023, 3.49512426, 2.70735166, 2.96614194, 3.49512426,
       3.49512426, 1.93689291, 3.67069698, 2.67242848, 3.49512426,
       3.10198469, 2.46096752, 0.49512426, 0.49512426, 0.49512426,
       0.59193348, 0.49512426, 2.63772182, 0.57041627, 0.49512426,
       0.49512426, 0.49512426, 0.79499188, 0.60033101, 0.49512426,
       0.49512426, 0.49512426, 0.76959902, 0.62340833, 0.49512426,
       0.49512426, 0.49512426, 0.49512426, 1.78972334, 3.49512426,
       1.72080809, 0.49512426, 0.49512426, 0.49512426, 0.52668735,
       0.54427244, 2.00115141, 0.49512426, 0.53842198, 0.        ,
       0.        , 0.        , 0.        , 0.02804374, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.06739038, 0.        , 0.00980845,
       0.        , 0.        , 0.        , 0.        , 0.05820102,
       0.        , 0.        , 0.        , 0.        , 0.     

In [84]:
idx = np.argsort(score)[-5:]

In [85]:
idx

array([ 4, 34,  1,  0,  7])

In [86]:
df.iloc[idx]

course                           section  \
4   data-engineering-zoomcamp  General course-related questions   
34  data-engineering-zoomcamp  General course-related questions   
1   data-engineering-zoomcamp  General course-related questions   
0   data-engineering-zoomcamp  General course-related questions   
7   data-engineering-zoomcamp  General course-related questions   

                                             question  \
4    Course - What can I do before the course starts?   
34               How can we contribute to the course?   
1   Course - What are the prerequisites for this c...   
0                Course - When will the course start?   
7   Course - Can I follow the course after it fini...   

                                                 text  
4   You can start by installing and setting up all...  
34  Star the repo! Share it with friends if you fi...  
1   GitHub - DataTalksClub data-engineering-zoomca...  
0   The purpose of this document is to capture fre...  
7   Yes, we will keep all the materials after the ...

In [87]:
class TextSearch:

    def __init__(self, text_fields):
        self.text_fields = text_fields
        self.matrices = {}
        self.vectorizers = {}

    def fit(self, records, vectorizer_params={}):
        self.df = pd.DataFrame(records)

        for f in self.text_fields:
            cv = TfidfVectorizer(**vectorizer_params)
            X = cv.fit_transform(self.df[f])
            self.matrices[f] = X
            self.vectorizers[f] = cv

    def search(self, query, n_results=10, boost={}, filters={}):
        score = np.zeros(len(self.df))

        for f in self.text_fields:
            b = boost.get(f, 1.0)
            q = self.vectorizers[f].transform([query])
            s = cosine_similarity(self.matrices[f], q).flatten()
            score = score + b * s

        for field, value in filters.items():
            mask = (self.df[field] == value).values
            score = score * mask

        idx = np.argsort(-score)[:n_results]
        results = self.df.iloc[idx]
        return results.to_dict(orient='records')

In [88]:
index = TextSearch(
    text_fields=['section', 'question', 'text']
)
index.fit(documents)

index.search(
    query='I just singned up. Is it too late to join the course?',
    n_results=5,
    boost={'question': 3.0},
    filters={'course': 'data-engineering-zoomcamp'}
)

[{'text': "Yes, even if you don't register, you're still eligible to submit the homeworks.\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything for the last minute.",
  'section': 'General course-related questions',
  'question': 'Course - Can I still join the course after the start date?',
  'course': 'data-engineering-zoomcamp'},
 {'text': "The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first  “Office Hours'' live.1\nSubscribe to course public Google Calendar (it works from Desktop only).\nRegister before the course starts using this link.\nJoin the course Telegram channel with announcements.\nDon’t forget to register in DataTalks.Club's Slack and join the channel.",
  'section': 'General course-related questions',
  'question': 'Course - When will the course start?',
  'course': 'data-engineerin

## SVD ##

In [89]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 23808 stored elements and shape (948, 1333)>

In [91]:
X.toarray().shape

(948, 1333)

In [92]:
from sklearn.decomposition import TruncatedSVD

X = matrices['text']
cv = vectorizers['text']

svd = TruncatedSVD(n_components=16)
X_emb = svd.fit_transform(X)

X_emb[0]

array([ 0.09652953, -0.08223719, -0.10263119, -0.07734604,  0.06983235,
       -0.05922701,  0.01643441, -0.13392553, -0.23966265,  0.30830078,
        0.03694493,  0.05199019, -0.15860661, -0.10202419, -0.00575041,
        0.05280283])

In [96]:
query = 'I just signed up. Is it too late to join the course?'

Q = cv.transform([query])
Q_emb = svd.transform(Q)
Q_emb[0]

array([ 0.05790238, -0.03851177, -0.05673254, -0.02722826,  0.04105491,
       -0.06105902,  0.00861605, -0.08700334, -0.16297745,  0.1978071 ,
        0.03571151,  0.04977411, -0.1008483 , -0.05741023,  0.00475762,
        0.02715919])

In [97]:
X_emb.shape, Q_emb.shape

((948, 16), (1, 16))

In [98]:
np.dot(X_emb[0], Q_emb[0])

np.float64(0.1621717635425392)

In [99]:
score = cosine_similarity(X_emb, Q_emb).flatten()
idx = np.argsort(-score)[:10]
list(df.loc[idx].text)

["The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first  “Office Hours'' live.1\nSubscribe to course public Google Calendar (it works from Desktop only).\nRegister before the course starts using this link.\nJoin the course Telegram channel with announcements.\nDon’t forget to register in DataTalks.Club's Slack and join the channel.",
 'The course videos are pre-recorded, you can start watching the course right now.\nWe will also occasionally have office hours - live sessions where we will answer your questions. The office hours sessions are recorded too.\nYou can see the office hours as well as the pre-recorded course videos in the course playlist on YouTube.',
 'If you have submitted two projects (and peer-reviewed at least 3 course-mates’ projects for each submission), you will get the certificate for the course. According to the course coordinator, Ale

In [100]:
df.loc[idx]

course                           section  \
0    data-engineering-zoomcamp  General course-related questions   
436  machine-learning-zoomcamp  General course-related questions   
764  machine-learning-zoomcamp   Projects (Midterm and Capstone)   
449  machine-learning-zoomcamp  General course-related questions   
15   data-engineering-zoomcamp  General course-related questions   
437  machine-learning-zoomcamp  General course-related questions   
814             mlops-zoomcamp        +-General course questions   
450  machine-learning-zoomcamp  General course-related questions   
11   data-engineering-zoomcamp  General course-related questions   
7    data-engineering-zoomcamp  General course-related questions   

                                              question  \
0                 Course - When will the course start?   
436                      Is it going to be live? When?   
764  What If I submitted only two projects and fail...   
449  The course has already started. Can I still jo...   
15   Homework - Are late submissions of homework al...   
437                          What if I miss a session?   
814  What if my answer is not exactly the same as t...   
450                When does the next iteration start?   
11   Certificate - Can I follow the course in a sel...   
7    Course - Can I follow the course after it fini...   

                                                  text  
0    The purpose of this document is to capture fre...  
436  The course videos are pre-recorded, you can st...  
764  If you have submitted two projects (and peer-r...  
449  Yes, you can. You won’t be able to submit some...  
15   No, late submissions are not allowed. But if t...  
437  Everything is recorded, so you won’t miss anyt...  
814  Please choose the closest one to your answer. ...  
450  The course is available in the self-paced mode...  
11   No, you can only get a certificate if you fini...  
7    Yes, we will keep all the materials after the ...

In [101]:
from sklearn.decomposition import NMF
nmf = NMF(n_components=16)
X_emb = nmf.fit_transform(X)
X_emb[0]

array([1.27731003e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.24211991e-04, 0.00000000e+00, 4.60488020e-04, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00])

In [102]:
Q = cv.transform([query])
Q_emb = nmf.transform(Q)
Q_emb[0]

array([0.08531163, 0.00194714, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.00208248,
       0.        ])

In [103]:
score = cosine_similarity(X_emb, Q_emb).flatten()
idx = np.argsort(-score)[:10]
list(df.loc[idx].text)

['The course videos are pre-recorded, you can start watching the course right now.\nWe will also occasionally have office hours - live sessions where we will answer your questions. The office hours sessions are recorded too.\nYou can see the office hours as well as the pre-recorded course videos in the course playlist on YouTube.',
 'Yes, you can. You won’t be able to submit some of the homeworks, but you can still take part in the course.\nIn order to get a certificate, you need to submit 2 out of 3 course projects and review 3 peers’ Projects by the deadline. It means that if you join the course at the end of November and manage to work on two projects, you will still be eligible for a certificate.',
 'If you have submitted two projects (and peer-reviewed at least 3 course-mates’ projects for each submission), you will get the certificate for the course. According to the course coordinator, Alexey Grigorev, only two projects are needed to get the course certificate.\n(optional) David

In [104]:
df.loc[idx]

course                           section  \
436  machine-learning-zoomcamp  General course-related questions   
449  machine-learning-zoomcamp  General course-related questions   
764  machine-learning-zoomcamp   Projects (Midterm and Capstone)   
814             mlops-zoomcamp        +-General course questions   
2    data-engineering-zoomcamp  General course-related questions   
0    data-engineering-zoomcamp  General course-related questions   
11   data-engineering-zoomcamp  General course-related questions   
451  machine-learning-zoomcamp  General course-related questions   
437  machine-learning-zoomcamp  General course-related questions   
7    data-engineering-zoomcamp  General course-related questions   

                                              question  \
436                      Is it going to be live? When?   
449  The course has already started. Can I still jo...   
764  What If I submitted only two projects and fail...   
814  What if my answer is not exactly the same as t...   
2    Course - Can I still join the course after the...   
0                 Course - When will the course start?   
11   Certificate - Can I follow the course in a sel...   
451      Can I submit the homework after the due date?   
437                          What if I miss a session?   
7    Course - Can I follow the course after it fini...   

                                                  text  
436  The course videos are pre-recorded, you can st...  
449  Yes, you can. You won’t be able to submit some...  
764  If you have submitted two projects (and peer-r...  
814  Please choose the closest one to your answer. ...  
2    Yes, even if you don't register, you're still ...  
0    The purpose of this document is to capture fre...  
11   No, you can only get a certificate if you fini...  
451  No, it’s not possible. The form is closed afte...  
437  Everything is recorded, so you won’t miss anyt...  
7    Yes, we will keep all the materials after the ...

In [105]:
import torch
from transformers import BertModel, BertTokenizer

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
model = BertModel.from_pretrained("bert-base-uncased")
model.eval()  # Set the model to evaluation mode if not training

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False

In [106]:
texts = [
    "Yes, we will keep all the materials after the course finishes.",
    "You can follow the course at your own pace after it finishes"
]
encoded_input = tokenizer(texts, padding=True, truncation=True, return_tensors='pt')

In [107]:
encoded_input

{'input_ids': tensor([[  101,  2748,  1010,  2057,  2097,  2562,  2035,  1996,  4475,  2044,
          1996,  2607, 12321,  1012,   102],
        [  101,  2017,  2064,  3582,  1996,  2607,  2012,  2115,  2219,  6393,
          2044,  2009, 12321,   102,     0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]])}

In [108]:
encoded_input['input_ids']

tensor([[  101,  2748,  1010,  2057,  2097,  2562,  2035,  1996,  4475,  2044,
          1996,  2607, 12321,  1012,   102],
        [  101,  2017,  2064,  3582,  1996,  2607,  2012,  2115,  2219,  6393,
          2044,  2009, 12321,   102,     0]])

In [109]:
with torch.no_grad():  # Disable gradient calculation for inference
    outputs = model(**encoded_input)
    hidden_states = outputs.last_hidden_state

In [110]:
outputs

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[ 1.0103e-01,  1.8106e-02,  1.3034e-01,  ..., -2.9319e-01,
           1.8632e-01,  6.6145e-01],
         [ 1.0608e+00, -1.2425e-01,  1.3701e-01,  ..., -1.6050e-01,
           1.0429e+00,  3.5325e-01],
         [ 1.8022e-01,  7.7588e-02,  3.9414e-01,  ..., -1.3787e-01,
           5.9744e-01,  1.7035e-01],
         ...,
         [ 4.7383e-01, -1.8445e-02,  2.1863e-01,  ..., -1.2885e-03,
          -8.3294e-02, -2.1699e-01],
         [ 6.5164e-01,  1.2163e-01, -2.4941e-01,  ...,  1.5567e-01,
          -5.6319e-01, -4.3100e-01],
         [ 7.1638e-01,  2.1572e-01, -2.8087e-02,  ...,  2.2812e-01,
          -6.7250e-01, -3.2448e-01]],

        [[ 3.1965e-01, -2.4620e-01,  1.9934e-01,  ..., -2.4255e-01,
          -1.0942e-01,  5.8847e-01],
         [-6.9823e-01, -7.5619e-01,  1.0645e-01,  ..., -1.1348e-01,
           4.5499e-01,  4.0241e-01],
         [ 4.1643e-01, -4.7885e-01,  3.2889e-01,  ..., -5.1462e-01,
           6.

In [111]:
outputs.keys()

odict_keys(['last_hidden_state', 'pooler_output'])

In [112]:
outputs.pooler_output

tensor([[-0.8582, -0.3924, -0.9297,  ..., -0.8452, -0.7236,  0.8645],
        [-0.7997, -0.1544,  0.0234,  ...,  0.0340, -0.6289,  0.8029]])

In [113]:
outputs.last_hidden_state

tensor([[[ 1.0103e-01,  1.8106e-02,  1.3034e-01,  ..., -2.9319e-01,
           1.8632e-01,  6.6145e-01],
         [ 1.0608e+00, -1.2425e-01,  1.3701e-01,  ..., -1.6050e-01,
           1.0429e+00,  3.5325e-01],
         [ 1.8022e-01,  7.7588e-02,  3.9414e-01,  ..., -1.3787e-01,
           5.9744e-01,  1.7035e-01],
         ...,
         [ 4.7383e-01, -1.8445e-02,  2.1863e-01,  ..., -1.2885e-03,
          -8.3294e-02, -2.1699e-01],
         [ 6.5164e-01,  1.2163e-01, -2.4941e-01,  ...,  1.5567e-01,
          -5.6319e-01, -4.3100e-01],
         [ 7.1638e-01,  2.1572e-01, -2.8087e-02,  ...,  2.2812e-01,
          -6.7250e-01, -3.2448e-01]],

        [[ 3.1965e-01, -2.4620e-01,  1.9934e-01,  ..., -2.4255e-01,
          -1.0942e-01,  5.8847e-01],
         [-6.9823e-01, -7.5619e-01,  1.0645e-01,  ..., -1.1348e-01,
           4.5499e-01,  4.0241e-01],
         [ 4.1643e-01, -4.7885e-01,  3.2889e-01,  ..., -5.1462e-01,
           6.5775e-02,  6.9717e-01],
         ...,
         [ 1.0277e-01, -8

In [114]:
outputs.last_hidden_state.shape

torch.Size([2, 15, 768])

In [115]:
outputs.pooler_output.shape

torch.Size([2, 768])

In [116]:
sentence_embeddings = hidden_states.mean(dim=1)
sentence_embeddings.shape

torch.Size([2, 768])

In [117]:
sentence_embeddings

tensor([[ 0.3600, -0.1607,  0.3545,  ...,  0.0429,  0.0348, -0.0382],
        [ 0.1785, -0.5000,  0.2528,  ..., -0.1141, -0.3361,  0.4110]])

In [119]:
X_emb = sentence_embeddings.numpy()

In [120]:
sentence_embeddings_cpu = sentence_embeddings.cpu()

In [121]:
def make_batches(seq, n):
    result = []
    for i in range(0, len(seq), n):
        batch = seq[i:i+n]
        result.append(batch)
    return result

In [126]:
from tqdm import tqdm
def compute_embeddings(texts, batch_size=8):
    text_batches = make_batches(texts, 8)
    
    all_embeddings = []
    
    for batch in tqdm(text_batches):
        encoded_input = tokenizer(batch, padding=True, truncation=True, return_tensors='pt')
    
        with torch.no_grad():
            outputs = model(**encoded_input)
            hidden_states = outputs.last_hidden_state
            
            batch_embeddings = hidden_states.mean(dim=1)
            batch_embeddings_np = batch_embeddings.cpu().numpy()
            all_embeddings.append(batch_embeddings_np)
    
    final_embeddings = np.vstack(all_embeddings)
    return final_embeddings

In [127]:
X_text = compute_embeddings(df['text'].tolist())

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 119/119 [11:01<00:00,  5.56s/it]


In [128]:
X_text.shape

(948, 768)

In [129]:
X_text[0]

array([-4.56302892e-03, -1.16675124e-01,  6.27471805e-01,  4.42592353e-02,
        2.69928187e-01, -2.77483314e-01,  1.63286597e-01,  4.64626551e-01,
        1.43439770e-01, -2.27813274e-01, -3.21897268e-01, -2.31939226e-01,
       -1.08724557e-01,  1.82816103e-01,  1.34099677e-01,  6.81395084e-02,
        6.79704994e-02,  4.16526683e-02, -4.92069870e-02,  2.94101425e-02,
        2.67369181e-01, -9.66819599e-02,  3.88590768e-02,  2.83335298e-01,
        3.79838914e-01,  2.01214358e-01, -1.00071952e-01,  4.45501171e-02,
       -4.26937222e-01, -2.33602270e-01,  1.32447153e-01, -2.06002682e-01,
        2.16875732e-01, -7.37486929e-02,  2.41626613e-02, -1.20170064e-01,
       -8.28266963e-02,  1.79647580e-01,  2.31271796e-02,  2.17579842e-01,
       -3.51695865e-01, -2.39214107e-01,  1.89373866e-01, -1.68018207e-01,
       -8.44550133e-02, -1.57881975e-01,  2.51900405e-01, -6.48412704e-02,
        6.54011369e-02, -1.15348503e-01, -2.74359882e-01,  4.13323015e-01,
        1.90569442e-02,  